name: Test Action
on: [push, pull_request]
jobs:
  test:
    concurrency:
      group: test-action
      cancel-in-progress: false

    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Test Init
        uses: ./
        with:
          args: init --author 'me' --fabric-latest --name 'test modpack' --version 0.1 --mc-version 1.21.1 --modloader fabric
      - name: Test Add Mod
        uses: ./
        with:
          args: modrinth add 'https://modrinth.com/mod/fabric-api'
      - name: Test Export Pack
        uses: ./
        with:
          args: modrinth export
